name: Deploy
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Added configurations to eliminate the Git 128 exit warning
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          show-progress: false

      - uses: actions/upload-pages-artifact@v5
        with:
          path: .

      - id: deployment
        uses: actions/deploy-pages@v5
